apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: worker
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      selector:
        matchLabels:
          node_status: drained
  selector:
    matchLabels:
      name: test-rollout
  template:
    metadata:
      labels:
        name: test-rollout
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["fobar"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
